export const LOCATION_DATA = {
  'United States': {
    code: 'US',
    flag: '🇺🇸',
    states: [
      { code: 'AL', name: 'Alabama', cities: ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville'] },
      { code: 'AK', name: 'Alaska', cities: ['Anchorage', 'Fairbanks', 'Juneau'] },
      { code: 'AZ', name: 'Arizona', cities: ['Phoenix', 'Tucson', 'Yuma', 'Mesa', 'Chandler', 'Scottsdale', 'Glendale', 'Gilbert'] },
      { code: 'AR', name: 'Arkansas', cities: ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale'] },
      { code: 'CA', name: 'California', cities: ['San Diego', 'Los Angeles', 'San Francisco', 'San Jose', 'Sacramento', 'Fresno', 'Oakland', 'Bakersfield', 'Anaheim', 'Santa Ana'] },
      { code: 'CO', name: 'Colorado', cities: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins'] },
      { code: 'CT', name: 'Connecticut', cities: ['Bridgeport', 'New Haven', 'Stamford', 'Hartford'] },
      { code: 'DE', name: 'Delaware', cities: ['Wilmington', 'Dover', 'Newark'] },
      { code: 'DC', name: 'District of Columbia', cities: ['Washington'] },
      { code: 'FL', name: 'Florida', cities: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Fort Lauderdale', 'Hialeah'] },
      { code: 'GA', name: 'Georgia', cities: ['Atlanta', 'Augusta', 'Columbus', 'Savannah'] },
      { code: 'HI', name: 'Hawaii', cities: ['Honolulu', 'Hilo', 'Kailua'] },
      { code: 'ID', name: 'Idaho', cities: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls'] },
      { code: 'IL', name: 'Illinois', cities: ['Chicago', 'Aurora', 'Naperville', 'Joliet', 'Rockford'] },
      { code: 'IN', name: 'Indiana', cities: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend'] },
      { code: 'IA', name: 'Iowa', cities: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City'] },
      { code: 'KS', name: 'Kansas', cities: ['Wichita', 'Overland Park', 'Kansas City', 'Topeka'] },
      { code: 'KY', name: 'Kentucky', cities: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro'] },
      { code: 'LA', name: 'Louisiana', cities: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette'] },
      { code: 'ME', name: 'Maine', cities: ['Portland', 'Lewiston', 'Bangor'] },
      { code: 'MD', name: 'Maryland', cities: ['Baltimore', 'Frederick', 'Rockville', 'Gaithersburg'] },
      { code: 'MA', name: 'Massachusetts', cities: ['Boston', 'Worcester', 'Springfield', 'Cambridge'] },
      { code: 'MI', name: 'Michigan', cities: ['Detroit', 'Grand Rapids', 'Warren', 'Ann Arbor'] },
      { code: 'MN', name: 'Minnesota', cities: ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth'] },
      { code: 'MS', name: 'Mississippi', cities: ['Jackson', 'Gulfport', 'Southaven', 'Biloxi'] },
      { code: 'MO', name: 'Missouri', cities: ['Kansas City', 'Saint Louis', 'Springfield', 'Columbia'] },
      { code: 'MT', name: 'Montana', cities: ['Billings', 'Missoula', 'Great Falls', 'Bozeman'] },
      { code: 'NE', name: 'Nebraska', cities: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island'] },
      { code: 'NV', name: 'Nevada', cities: ['Las Vegas', 'Reno', 'Henderson', 'North Las Vegas', 'Sparks'] },
      { code: 'NH', name: 'New Hampshire', cities: ['Manchester', 'Nashua', 'Concord'] },
      { code: 'NJ', name: 'New Jersey', cities: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth'] },
      { code: 'NM', name: 'New Mexico', cities: ['Albuquerque', 'Las Cruces', 'Santa Fe', 'Roswell'] },
      { code: 'NY', name: 'New York', cities: ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse'] },
      { code: 'NC', name: 'North Carolina', cities: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham'] },
      { code: 'ND', name: 'North Dakota', cities: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot'] },
      { code: 'OH', name: 'Ohio', cities: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'] },
      { code: 'OK', name: 'Oklahoma', cities: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow'] },
      { code: 'OR', name: 'Oregon', cities: ['Portland', 'Salem', 'Eugene', 'Gresham'] },
      { code: 'PA', name: 'Pennsylvania', cities: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie'] },
      { code: 'RI', name: 'Rhode Island', cities: ['Providence', 'Warwick', 'Cranston'] },
      { code: 'SC', name: 'South Carolina', cities: ['Charleston', 'Columbia', 'North Charleston', 'Mount Pleasant'] },
      { code: 'SD', name: 'South Dakota', cities: ['Sioux Falls', 'Rapid City', 'Aberdeen'] },
      { code: 'TN', name: 'Tennessee', cities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga'] },
      { code: 'TX', name: 'Texas', cities: ['El Paso', 'Houston', 'San Antonio', 'Dallas', 'Austin', 'McAllen', 'Laredo', 'Brownsville', 'Fort Worth', 'Arlington'] },
      { code: 'UT', name: 'Utah', cities: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan'] },
      { code: 'VT', name: 'Vermont', cities: ['Burlington', 'South Burlington', 'Rutland'] },
      { code: 'VA', name: 'Virginia', cities: ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond'] },
      { code: 'WA', name: 'Washington', cities: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'] },
      { code: 'WV', name: 'West Virginia', cities: ['Charleston', 'Huntington', 'Morgantown'] },
      { code: 'WI', name: 'Wisconsin', cities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha'] },
      { code: 'WY', name: 'Wyoming', cities: ['Cheyenne', 'Casper', 'Laramie'] },
    ]
  },
  'México': {
    code: 'MX',
    flag: '🇲🇽',
    states: [
      { code: 'BC', name: 'Baja California', cities: ['Tijuana', 'Mexicali', 'Ensenada', 'Tecate', 'Playas de Rosarito', 'San Quintín'] },
      { code: 'CHH', name: 'Chihuahua', cities: ['Ciudad Juárez', 'Chihuahua', 'Delicias', 'Cuauhtémoc', 'Parral'] },
      { code: 'SON', name: 'Sonora', cities: ['Nogales', 'Hermosillo', 'Ciudad Obregón', 'San Luis Río Colorado', 'Agua Prieta', 'Guaymas'] },
      { code: 'COA', name: 'Coahuila', cities: ['Saltillo', 'Torreón', 'Monclova', 'Piedras Negras', 'Ciudad Acuña'] },
      { code: 'TAM', name: 'Tamaulipas', cities: ['Reynosa', 'Matamoros', 'Nuevo Laredo', 'Tampico', 'Ciudad Victoria', 'Ciudad Madero'] },
      { code: 'NL', name: 'Nuevo León', cities: ['Monterrey', 'San Pedro Garza García', 'Apodaca', 'Guadalupe', 'San Nicolás de los Garza', 'General Escobedo'] },
      { code: 'JAL', name: 'Jalisco', cities: ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Tonalá', 'Puerto Vallarta', 'Ciudad Guzmán'] },
      { code: 'CDMX', name: 'Ciudad de México', cities: ['Ciudad de México', 'Cuauhtémoc', 'Iztapalapa', 'Coyoacán', 'Miguel Hidalgo', 'Benito Juárez'] },
      { code: 'MEX', name: 'Estado de México', cities: ['Toluca', 'Naucalpan', 'Ecatepec', 'Tlalnepantla', 'Nezahualcóyotl', 'Chimalhuacán'] },
      { code: 'SIN', name: 'Sinaloa', cities: ['Culiacán', 'Mazatlán', 'Los Mochis', 'Guasave'] },
      { code: 'QRO', name: 'Querétaro', cities: ['Santiago de Querétaro', 'San Juan del Río', 'El Marqués'] },
      { code: 'GUA', name: 'Guanajuato', cities: ['Leon', 'Irapuato', 'Celaya', 'Guanajuato', 'San Miguel de Allende'] },
      { code: 'PUE', name: 'Puebla', cities: ['Puebla', 'San Andrés Cholula', 'Tehuacán'] },
      { code: 'VER', name: 'Veracruz', cities: ['Veracruz', 'Xalapa', 'Coatzacoalcos', 'Poza Rica'] },
      { code: 'YUC', name: 'Yucatán', cities: ['Mérida', 'Kanasín', 'Valladolid'] },
    ]
  },
  'Canada': {
    code: 'CA',
    flag: '🇨🇦',
    states: [
      { code: 'ON', name: 'Ontario', cities: ['Toronto', 'Ottawa', 'Mississauga', 'Brampton', 'Hamilton'] },
      { code: 'BC', name: 'British Columbia', cities: ['Vancouver', 'Surrey', 'Burnaby', 'Richmond', 'Victoria'] },
      { code: 'QC', name: 'Quebec', cities: ['Montreal', 'Quebec City', 'Laval', 'Gatineau'] },
      { code: 'AB', name: 'Alberta', cities: ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge'] },
    ]
  }
};
